version: 2
jobs:
  build:

    working_directory: ~/FeedbackSystem # directory where all steps will run

    docker:
      - image: circleci/openjdk:11.0.2-jdk-stretch
      - image: circleci/postgres:10.1

    branches:
      only:
        - master
        - develop
    
    steps:
      - checkout # check out soruce code to working directory

      - restore_cache:
          key: FeedbackSystem-{{ checksum "pom.xml" }}

      - run: 
          name: Get the project dependencies
          command: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: FeedbackSystem-{{ checksum "pom.xml" }}

      - run:
          name: Run tests
          command: mvn package
      
      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/FeedbackSystem-0.0.1-SNAPSHOT.jar